// Code generated by MockGen. DO NOT EDIT.
// Source: submitter/expected_anon_client.go

// Package submitter is a generated GoMock package.
package submitter

import (
	reflect "reflect"

	types "github.com/anon-org/anon/v4/x/btccheckpoint/types"
	types0 "github.com/anon-org/anon/v4/x/checkpointing/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	gomock "github.com/golang/mock/gomock"
)

// MockAnonQueryClient is a mock of AnonQueryClient interface.
type MockAnonQueryClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnonQueryClientMockRecorder
}

// MockAnonQueryClientMockRecorder is the mock recorder for MockAnonQueryClient.
type MockAnonQueryClientMockRecorder struct {
	mock *MockAnonQueryClient
}

// NewMockAnonQueryClient creates a new mock instance.
func NewMockAnonQueryClient(ctrl *gomock.Controller) *MockAnonQueryClient {
	mock := &MockAnonQueryClient{ctrl: ctrl}
	mock.recorder = &MockAnonQueryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonQueryClient) EXPECT() *MockAnonQueryClientMockRecorder {
	return m.recorder
}

// BTCCheckpointParams mocks base method.
func (m *MockAnonQueryClient) BTCCheckpointParams() (*types.QueryParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCCheckpointParams")
	ret0, _ := ret[0].(*types.QueryParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCCheckpointParams indicates an expected call of BTCCheckpointParams.
func (mr *MockAnonQueryClientMockRecorder) BTCCheckpointParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCCheckpointParams", reflect.TypeOf((*MockAnonQueryClient)(nil).BTCCheckpointParams))
}

// RawCheckpointList mocks base method.
func (m *MockAnonQueryClient) RawCheckpointList(status types0.CheckpointStatus, pagination *query.PageRequest) (*types0.QueryRawCheckpointListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawCheckpointList", status, pagination)
	ret0, _ := ret[0].(*types0.QueryRawCheckpointListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawCheckpointList indicates an expected call of RawCheckpointList.
func (mr *MockAnonQueryClientMockRecorder) RawCheckpointList(status, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawCheckpointList", reflect.TypeOf((*MockAnonQueryClient)(nil).RawCheckpointList), status, pagination)
}
