// Code generated by MockGen. DO NOT EDIT.
// Source: btcstaking-tracker/stakingeventwatcher/expected_anon_client.go

// Package stakingeventwatcher is a generated GoMock package.
package stakingeventwatcher

import (
	context "context"
	reflect "reflect"

	types "github.com/anon-org/anon/v4/x/btccheckpoint/types"
	types0 "github.com/anon-org/anon/v4/x/btcstaking/types"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	wire "github.com/btcsuite/btcd/wire"
	gomock "github.com/golang/mock/gomock"
)

// MockAnonNodeAdapter is a mock of AnonNodeAdapter interface.
type MockAnonNodeAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAnonNodeAdapterMockRecorder
}

// MockAnonNodeAdapterMockRecorder is the mock recorder for MockAnonNodeAdapter.
type MockAnonNodeAdapterMockRecorder struct {
	mock *MockAnonNodeAdapter
}

// NewMockAnonNodeAdapter creates a new mock instance.
func NewMockAnonNodeAdapter(ctrl *gomock.Controller) *MockAnonNodeAdapter {
	mock := &MockAnonNodeAdapter{ctrl: ctrl}
	mock.recorder = &MockAnonNodeAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonNodeAdapter) EXPECT() *MockAnonNodeAdapterMockRecorder {
	return m.recorder
}

// ActivateDelegation mocks base method.
func (m *MockAnonNodeAdapter) ActivateDelegation(ctx context.Context, stakingTxHash chainhash.Hash, proof *types.BTCSpvProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateDelegation", ctx, stakingTxHash, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateDelegation indicates an expected call of ActivateDelegation.
func (mr *MockAnonNodeAdapterMockRecorder) ActivateDelegation(ctx, stakingTxHash, proof interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateDelegation", reflect.TypeOf((*MockAnonNodeAdapter)(nil).ActivateDelegation), ctx, stakingTxHash, proof)
}

// BTCDelegation mocks base method.
func (m *MockAnonNodeAdapter) BTCDelegation(stakingTxHash string) (*Delegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegation", stakingTxHash)
	ret0, _ := ret[0].(*Delegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegation indicates an expected call of BTCDelegation.
func (mr *MockAnonNodeAdapterMockRecorder) BTCDelegation(stakingTxHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegation", reflect.TypeOf((*MockAnonNodeAdapter)(nil).BTCDelegation), stakingTxHash)
}

// BtcClientTipHeight mocks base method.
func (m *MockAnonNodeAdapter) BtcClientTipHeight() (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BtcClientTipHeight")
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BtcClientTipHeight indicates an expected call of BtcClientTipHeight.
func (mr *MockAnonNodeAdapterMockRecorder) BtcClientTipHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BtcClientTipHeight", reflect.TypeOf((*MockAnonNodeAdapter)(nil).BtcClientTipHeight))
}

// CometBFTTipHeight mocks base method.
func (m *MockAnonNodeAdapter) CometBFTTipHeight(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CometBFTTipHeight", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CometBFTTipHeight indicates an expected call of CometBFTTipHeight.
func (mr *MockAnonNodeAdapterMockRecorder) CometBFTTipHeight(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CometBFTTipHeight", reflect.TypeOf((*MockAnonNodeAdapter)(nil).CometBFTTipHeight), ctx)
}

// DelegationsByStatus mocks base method.
func (m *MockAnonNodeAdapter) DelegationsByStatus(status types0.BTCDelegationStatus, cursor []byte, limit uint64) ([]Delegation, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegationsByStatus", status, cursor, limit)
	ret0, _ := ret[0].([]Delegation)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DelegationsByStatus indicates an expected call of DelegationsByStatus.
func (mr *MockAnonNodeAdapterMockRecorder) DelegationsByStatus(status, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegationsByStatus", reflect.TypeOf((*MockAnonNodeAdapter)(nil).DelegationsByStatus), status, cursor, limit)
}

// DelegationsModifiedInBlock mocks base method.
func (m *MockAnonNodeAdapter) DelegationsModifiedInBlock(ctx context.Context, height int64, eventTypes []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegationsModifiedInBlock", ctx, height, eventTypes)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DelegationsModifiedInBlock indicates an expected call of DelegationsModifiedInBlock.
func (mr *MockAnonNodeAdapterMockRecorder) DelegationsModifiedInBlock(ctx, height, eventTypes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegationsModifiedInBlock", reflect.TypeOf((*MockAnonNodeAdapter)(nil).DelegationsModifiedInBlock), ctx, height, eventTypes)
}

// IsDelegationActive mocks base method.
func (m *MockAnonNodeAdapter) IsDelegationActive(stakingTxHash chainhash.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDelegationActive", stakingTxHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDelegationActive indicates an expected call of IsDelegationActive.
func (mr *MockAnonNodeAdapterMockRecorder) IsDelegationActive(stakingTxHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDelegationActive", reflect.TypeOf((*MockAnonNodeAdapter)(nil).IsDelegationActive), stakingTxHash)
}

// IsDelegationVerified mocks base method.
func (m *MockAnonNodeAdapter) IsDelegationVerified(stakingTxHash chainhash.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDelegationVerified", stakingTxHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDelegationVerified indicates an expected call of IsDelegationVerified.
func (mr *MockAnonNodeAdapterMockRecorder) IsDelegationVerified(stakingTxHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDelegationVerified", reflect.TypeOf((*MockAnonNodeAdapter)(nil).IsDelegationVerified), stakingTxHash)
}

// Params mocks base method.
func (m *MockAnonNodeAdapter) Params() (*AnonParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Params")
	ret0, _ := ret[0].(*AnonParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Params indicates an expected call of Params.
func (mr *MockAnonNodeAdapterMockRecorder) Params() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Params", reflect.TypeOf((*MockAnonNodeAdapter)(nil).Params))
}

// QueryHeaderDepth mocks base method.
func (m *MockAnonNodeAdapter) QueryHeaderDepth(headerHash *chainhash.Hash) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryHeaderDepth", headerHash)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryHeaderDepth indicates an expected call of QueryHeaderDepth.
func (mr *MockAnonNodeAdapterMockRecorder) QueryHeaderDepth(headerHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryHeaderDepth", reflect.TypeOf((*MockAnonNodeAdapter)(nil).QueryHeaderDepth), headerHash)
}

// ReportUnbonding mocks base method.
func (m *MockAnonNodeAdapter) ReportUnbonding(ctx context.Context, stakingTxHash chainhash.Hash, stakeSpendingTx *wire.MsgTx, inclusionProof *types0.InclusionProof, fundingTxs [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportUnbonding", ctx, stakingTxHash, stakeSpendingTx, inclusionProof, fundingTxs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportUnbonding indicates an expected call of ReportUnbonding.
func (mr *MockAnonNodeAdapterMockRecorder) ReportUnbonding(ctx, stakingTxHash, stakeSpendingTx, inclusionProof, fundingTxs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportUnbonding", reflect.TypeOf((*MockAnonNodeAdapter)(nil).ReportUnbonding), ctx, stakingTxHash, stakeSpendingTx, inclusionProof, fundingTxs)
}
