// Code generated by MockGen. DO NOT EDIT.
// Source: monitor/expected_anon_client.go

// Package monitor is a generated GoMock package.
package monitor

import (
	reflect "reflect"

	types "github.com/anon-org/anon/v4/x/btclightclient/types"
	types0 "github.com/anon-org/anon/v4/x/checkpointing/types"
	types1 "github.com/anon-org/anon/v4/x/epoching/types"
	types2 "github.com/anon-org/anon/v4/x/monitor/types"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	query "github.com/cosmos/cosmos-sdk/types/query"
	gomock "github.com/golang/mock/gomock"
)

// MockAnonQueryClient is a mock of AnonQueryClient interface.
type MockAnonQueryClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnonQueryClientMockRecorder
}

// MockAnonQueryClientMockRecorder is the mock recorder for MockAnonQueryClient.
type MockAnonQueryClientMockRecorder struct {
	mock *MockAnonQueryClient
}

// NewMockAnonQueryClient creates a new mock instance.
func NewMockAnonQueryClient(ctrl *gomock.Controller) *MockAnonQueryClient {
	mock := &MockAnonQueryClient{ctrl: ctrl}
	mock.recorder = &MockAnonQueryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonQueryClient) EXPECT() *MockAnonQueryClientMockRecorder {
	return m.recorder
}

// BTCHeaderChainTip mocks base method.
func (m *MockAnonQueryClient) BTCHeaderChainTip() (*types.QueryTipResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCHeaderChainTip")
	ret0, _ := ret[0].(*types.QueryTipResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCHeaderChainTip indicates an expected call of BTCHeaderChainTip.
func (mr *MockAnonQueryClientMockRecorder) BTCHeaderChainTip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCHeaderChainTip", reflect.TypeOf((*MockAnonQueryClient)(nil).BTCHeaderChainTip))
}

// BlsPublicKeyList mocks base method.
func (m *MockAnonQueryClient) BlsPublicKeyList(epochNumber uint64, pagination *query.PageRequest) (*types0.QueryBlsPublicKeyListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlsPublicKeyList", epochNumber, pagination)
	ret0, _ := ret[0].(*types0.QueryBlsPublicKeyListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlsPublicKeyList indicates an expected call of BlsPublicKeyList.
func (mr *MockAnonQueryClientMockRecorder) BlsPublicKeyList(epochNumber, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlsPublicKeyList", reflect.TypeOf((*MockAnonQueryClient)(nil).BlsPublicKeyList), epochNumber, pagination)
}

// ContainsBTCBlock mocks base method.
func (m *MockAnonQueryClient) ContainsBTCBlock(blockHash *chainhash.Hash) (*types.QueryContainsBytesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsBTCBlock", blockHash)
	ret0, _ := ret[0].(*types.QueryContainsBytesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainsBTCBlock indicates an expected call of ContainsBTCBlock.
func (mr *MockAnonQueryClientMockRecorder) ContainsBTCBlock(blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsBTCBlock", reflect.TypeOf((*MockAnonQueryClient)(nil).ContainsBTCBlock), blockHash)
}

// CurrentEpoch mocks base method.
func (m *MockAnonQueryClient) CurrentEpoch() (*types1.QueryCurrentEpochResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentEpoch")
	ret0, _ := ret[0].(*types1.QueryCurrentEpochResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentEpoch indicates an expected call of CurrentEpoch.
func (mr *MockAnonQueryClientMockRecorder) CurrentEpoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentEpoch", reflect.TypeOf((*MockAnonQueryClient)(nil).CurrentEpoch))
}

// EndedEpochBTCHeight mocks base method.
func (m *MockAnonQueryClient) EndedEpochBTCHeight(epochNum uint64) (*types2.QueryEndedEpochBtcHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndedEpochBTCHeight", epochNum)
	ret0, _ := ret[0].(*types2.QueryEndedEpochBtcHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndedEpochBTCHeight indicates an expected call of EndedEpochBTCHeight.
func (mr *MockAnonQueryClientMockRecorder) EndedEpochBTCHeight(epochNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndedEpochBTCHeight", reflect.TypeOf((*MockAnonQueryClient)(nil).EndedEpochBTCHeight), epochNum)
}

// IsRunning mocks base method.
func (m *MockAnonQueryClient) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockAnonQueryClientMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockAnonQueryClient)(nil).IsRunning))
}

// RawCheckpoint mocks base method.
func (m *MockAnonQueryClient) RawCheckpoint(epochNumber uint64) (*types0.QueryRawCheckpointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawCheckpoint", epochNumber)
	ret0, _ := ret[0].(*types0.QueryRawCheckpointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawCheckpoint indicates an expected call of RawCheckpoint.
func (mr *MockAnonQueryClientMockRecorder) RawCheckpoint(epochNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawCheckpoint", reflect.TypeOf((*MockAnonQueryClient)(nil).RawCheckpoint), epochNumber)
}

// ReportedCheckpointBTCHeight mocks base method.
func (m *MockAnonQueryClient) ReportedCheckpointBTCHeight(hashStr string) (*types2.QueryReportedCheckpointBtcHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportedCheckpointBTCHeight", hashStr)
	ret0, _ := ret[0].(*types2.QueryReportedCheckpointBtcHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportedCheckpointBTCHeight indicates an expected call of ReportedCheckpointBTCHeight.
func (mr *MockAnonQueryClientMockRecorder) ReportedCheckpointBTCHeight(hashStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportedCheckpointBTCHeight", reflect.TypeOf((*MockAnonQueryClient)(nil).ReportedCheckpointBTCHeight), hashStr)
}

// Start mocks base method.
func (m *MockAnonQueryClient) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAnonQueryClientMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAnonQueryClient)(nil).Start))
}

// Stop mocks base method.
func (m *MockAnonQueryClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAnonQueryClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAnonQueryClient)(nil).Stop))
}
