// Code generated by MockGen. DO NOT EDIT.
// Source: reporter/expected_anon_client.go

// Package reporter is a generated GoMock package.
package reporter

import (
	context "context"
	reflect "reflect"

	errors "cosmossdk.io/errors"
	anonclient "github.com/anon-org/anon/v4/client/anonclient"
	config "github.com/anon-org/anon/v4/client/config"
	types "github.com/anon-org/anon/v4/x/btccheckpoint/types"
	types0 "github.com/anon-org/anon/v4/x/btclightclient/types"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	types1 "github.com/cosmos/cosmos-sdk/types"
	gomock "github.com/golang/mock/gomock"
)

// MockAnonClient is a mock of AnonClient interface.
type MockAnonClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnonClientMockRecorder
}

// MockAnonClientMockRecorder is the mock recorder for MockAnonClient.
type MockAnonClientMockRecorder struct {
	mock *MockAnonClient
}

// NewMockAnonClient creates a new mock instance.
func NewMockAnonClient(ctrl *gomock.Controller) *MockAnonClient {
	mock := &MockAnonClient{ctrl: ctrl}
	mock.recorder = &MockAnonClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonClient) EXPECT() *MockAnonClientMockRecorder {
	return m.recorder
}

// BTCBaseHeader mocks base method.
func (m *MockAnonClient) BTCBaseHeader() (*types0.QueryBaseHeaderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCBaseHeader")
	ret0, _ := ret[0].(*types0.QueryBaseHeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCBaseHeader indicates an expected call of BTCBaseHeader.
func (mr *MockAnonClientMockRecorder) BTCBaseHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCBaseHeader", reflect.TypeOf((*MockAnonClient)(nil).BTCBaseHeader))
}

// BTCCheckpointParams mocks base method.
func (m *MockAnonClient) BTCCheckpointParams() (*types.QueryParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCCheckpointParams")
	ret0, _ := ret[0].(*types.QueryParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCCheckpointParams indicates an expected call of BTCCheckpointParams.
func (mr *MockAnonClientMockRecorder) BTCCheckpointParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCCheckpointParams", reflect.TypeOf((*MockAnonClient)(nil).BTCCheckpointParams))
}

// BTCHeaderChainTip mocks base method.
func (m *MockAnonClient) BTCHeaderChainTip() (*types0.QueryTipResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCHeaderChainTip")
	ret0, _ := ret[0].(*types0.QueryTipResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCHeaderChainTip indicates an expected call of BTCHeaderChainTip.
func (mr *MockAnonClientMockRecorder) BTCHeaderChainTip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCHeaderChainTip", reflect.TypeOf((*MockAnonClient)(nil).BTCHeaderChainTip))
}

// ContainsBTCBlock mocks base method.
func (m *MockAnonClient) ContainsBTCBlock(blockHash *chainhash.Hash) (*types0.QueryContainsBytesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsBTCBlock", blockHash)
	ret0, _ := ret[0].(*types0.QueryContainsBytesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainsBTCBlock indicates an expected call of ContainsBTCBlock.
func (mr *MockAnonClientMockRecorder) ContainsBTCBlock(blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsBTCBlock", reflect.TypeOf((*MockAnonClient)(nil).ContainsBTCBlock), blockHash)
}

// GetConfig mocks base method.
func (m *MockAnonClient) GetConfig() *config.AnonConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*config.AnonConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockAnonClientMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockAnonClient)(nil).GetConfig))
}

// InsertBTCSpvProof mocks base method.
func (m *MockAnonClient) InsertBTCSpvProof(ctx context.Context, msg *types.MsgInsertBTCSpvProof) (*anonclient.RelayerTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBTCSpvProof", ctx, msg)
	ret0, _ := ret[0].(*anonclient.RelayerTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBTCSpvProof indicates an expected call of InsertBTCSpvProof.
func (mr *MockAnonClientMockRecorder) InsertBTCSpvProof(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBTCSpvProof", reflect.TypeOf((*MockAnonClient)(nil).InsertBTCSpvProof), ctx, msg)
}

// InsertHeaders mocks base method.
func (m *MockAnonClient) InsertHeaders(ctx context.Context, msgs *types0.MsgInsertHeaders) (*anonclient.RelayerTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHeaders", ctx, msgs)
	ret0, _ := ret[0].(*anonclient.RelayerTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertHeaders indicates an expected call of InsertHeaders.
func (mr *MockAnonClientMockRecorder) InsertHeaders(ctx, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHeaders", reflect.TypeOf((*MockAnonClient)(nil).InsertHeaders), ctx, msgs)
}

// MustGetAddr mocks base method.
func (m *MockAnonClient) MustGetAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustGetAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// MustGetAddr indicates an expected call of MustGetAddr.
func (mr *MockAnonClientMockRecorder) MustGetAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetAddr", reflect.TypeOf((*MockAnonClient)(nil).MustGetAddr))
}

// ReliablySendMsg mocks base method.
func (m *MockAnonClient) ReliablySendMsg(ctx context.Context, msg types1.Msg, expectedErrors, unrecoverableErrors []*errors.Error) (*anonclient.RelayerTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReliablySendMsg", ctx, msg, expectedErrors, unrecoverableErrors)
	ret0, _ := ret[0].(*anonclient.RelayerTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReliablySendMsg indicates an expected call of ReliablySendMsg.
func (mr *MockAnonClientMockRecorder) ReliablySendMsg(ctx, msg, expectedErrors, unrecoverableErrors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReliablySendMsg", reflect.TypeOf((*MockAnonClient)(nil).ReliablySendMsg), ctx, msg, expectedErrors, unrecoverableErrors)
}

// Stop mocks base method.
func (m *MockAnonClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAnonClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAnonClient)(nil).Stop))
}
