// Code generated by MockGen. DO NOT EDIT.
// Source: btcstaking-tracker/atomicslasher/expected_anon_client.go

// Package atomicslasher is a generated GoMock package.
package atomicslasher

import (
	context "context"
	reflect "reflect"

	errors "cosmossdk.io/errors"
	anonclient "github.com/anon-org/anon/v4/client/anonclient"
	types "github.com/anon-org/anon/v4/x/btcstaking/types"
	types0 "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	gomock "github.com/golang/mock/gomock"
)

// MockAnonClient is a mock of AnonClient interface.
type MockAnonClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnonClientMockRecorder
}

// MockAnonClientMockRecorder is the mock recorder for MockAnonClient.
type MockAnonClientMockRecorder struct {
	mock *MockAnonClient
}

// NewMockAnonClient creates a new mock instance.
func NewMockAnonClient(ctrl *gomock.Controller) *MockAnonClient {
	mock := &MockAnonClient{ctrl: ctrl}
	mock.recorder = &MockAnonClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonClient) EXPECT() *MockAnonClientMockRecorder {
	return m.recorder
}

// BTCDelegation mocks base method.
func (m *MockAnonClient) BTCDelegation(stakingTxHashHex string) (*types.QueryBTCDelegationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegation", stakingTxHashHex)
	ret0, _ := ret[0].(*types.QueryBTCDelegationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegation indicates an expected call of BTCDelegation.
func (mr *MockAnonClientMockRecorder) BTCDelegation(stakingTxHashHex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegation", reflect.TypeOf((*MockAnonClient)(nil).BTCDelegation), stakingTxHashHex)
}

// BTCDelegations mocks base method.
func (m *MockAnonClient) BTCDelegations(status types.BTCDelegationStatus, pagination *query.PageRequest) (*types.QueryBTCDelegationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegations", status, pagination)
	ret0, _ := ret[0].(*types.QueryBTCDelegationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegations indicates an expected call of BTCDelegations.
func (mr *MockAnonClientMockRecorder) BTCDelegations(status, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegations", reflect.TypeOf((*MockAnonClient)(nil).BTCDelegations), status, pagination)
}

// BTCStakingParamsByVersion mocks base method.
func (m *MockAnonClient) BTCStakingParamsByVersion(version uint32) (*types.QueryParamsByVersionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCStakingParamsByVersion", version)
	ret0, _ := ret[0].(*types.QueryParamsByVersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCStakingParamsByVersion indicates an expected call of BTCStakingParamsByVersion.
func (mr *MockAnonClientMockRecorder) BTCStakingParamsByVersion(version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCStakingParamsByVersion", reflect.TypeOf((*MockAnonClient)(nil).BTCStakingParamsByVersion), version)
}

// FinalityProvider mocks base method.
func (m *MockAnonClient) FinalityProvider(fpBtcPkHex string) (*types.QueryFinalityProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalityProvider", fpBtcPkHex)
	ret0, _ := ret[0].(*types.QueryFinalityProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalityProvider indicates an expected call of FinalityProvider.
func (mr *MockAnonClientMockRecorder) FinalityProvider(fpBtcPkHex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalityProvider", reflect.TypeOf((*MockAnonClient)(nil).FinalityProvider), fpBtcPkHex)
}

// MustGetAddr mocks base method.
func (m *MockAnonClient) MustGetAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustGetAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// MustGetAddr indicates an expected call of MustGetAddr.
func (mr *MockAnonClientMockRecorder) MustGetAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetAddr", reflect.TypeOf((*MockAnonClient)(nil).MustGetAddr))
}

// ReliablySendMsg mocks base method.
func (m *MockAnonClient) ReliablySendMsg(ctx context.Context, msg types0.Msg, expectedErrors, unrecoverableErrors []*errors.Error) (*anonclient.RelayerTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReliablySendMsg", ctx, msg, expectedErrors, unrecoverableErrors)
	ret0, _ := ret[0].(*anonclient.RelayerTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReliablySendMsg indicates an expected call of ReliablySendMsg.
func (mr *MockAnonClientMockRecorder) ReliablySendMsg(ctx, msg, expectedErrors, unrecoverableErrors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReliablySendMsg", reflect.TypeOf((*MockAnonClient)(nil).ReliablySendMsg), ctx, msg, expectedErrors, unrecoverableErrors)
}
